no he podido arreglar esto
Caused by: KafkaJSConnectionError: Connection error: getaddrinfo
ENOTFOUND 425736b218c3    at Socket.onError
(/home/kamilo/programming/kafka/node_modules/kafkajs/src/network/connection.js:210:23)
... 3 lines matching cause stack trace ...    at
process.processTicksAndRejections
(node:internal/process/task_queues:82:21) {  name:
'KafkaJSNumberOfRetriesExceeded',  retriable: false,  helpUrl:
undefined,  retryCount: 5,  retryTime: 6248,  [cause]:
KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND
425736b218c3      at Socket.onError
(/home/kamilo/programming/kafka/node_modules/kafkajs/src/network/connection.js:210:23)
at Socket.emit (node:events:519:28)      at emitErrorNT
(node:internal/streams/destroy:169:8)      at emitErrorCloseNT
(node:internal/streams/destroy:128:3)      at
process.processTicksAndRejections
(node:internal/process/task_queues:82:21) {    retriable: true,
helpUrl: undefined,    broker: '425736b218c3:9092',    code:
'ENOTFOUND',    [cause]: undefined  }}